-- Add monetization fields to Show table in both organization schemas

-- org_podcastflow_pro schema
ALTER TABLE org_podcastflow_pro."Show"
ADD COLUMN IF NOT EXISTS "pricingModel" TEXT DEFAULT 'cpm',
ADD COLUMN IF NOT EXISTS "preRollSlots" INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS "midRollSlots" INTEGER DEFAULT 2,
ADD COLUMN IF NOT EXISTS "postRollSlots" INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS "preRollCpm" DECIMAL(10,2) DEFAULT 25.00,
ADD COLUMN IF NOT EXISTS "midRollCpm" DECIMAL(10,2) DEFAULT 30.00,
ADD COLUMN IF NOT EXISTS "postRollCpm" DECIMAL(10,2) DEFAULT 20.00,
ADD COLUMN IF NOT EXISTS "preRollSpotCost" DECIMAL(10,2) DEFAULT 500.00,
ADD COLUMN IF NOT EXISTS "midRollSpotCost" DECIMAL(10,2) DEFAULT 750.00,
ADD COLUMN IF NOT EXISTS "postRollSpotCost" DECIMAL(10,2) DEFAULT 400.00,
ADD COLUMN IF NOT EXISTS "avgEpisodeDownloads" INTEGER DEFAULT 5000;

-- org_unfy schema
ALTER TABLE org_unfy."Show"
ADD COLUMN IF NOT EXISTS "pricingModel" TEXT DEFAULT 'cpm',
ADD COLUMN IF NOT EXISTS "preRollSlots" INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS "midRollSlots" INTEGER DEFAULT 2,
ADD COLUMN IF NOT EXISTS "postRollSlots" INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS "preRollCpm" DECIMAL(10,2) DEFAULT 25.00,
ADD COLUMN IF NOT EXISTS "midRollCpm" DECIMAL(10,2) DEFAULT 30.00,
ADD COLUMN IF NOT EXISTS "postRollCpm" DECIMAL(10,2) DEFAULT 20.00,
ADD COLUMN IF NOT EXISTS "preRollSpotCost" DECIMAL(10,2) DEFAULT 500.00,
ADD COLUMN IF NOT EXISTS "midRollSpotCost" DECIMAL(10,2) DEFAULT 750.00,
ADD COLUMN IF NOT EXISTS "postRollSpotCost" DECIMAL(10,2) DEFAULT 400.00,
ADD COLUMN IF NOT EXISTS "avgEpisodeDownloads" INTEGER DEFAULT 5000;

-- Add check constraint for pricingModel
ALTER TABLE org_podcastflow_pro."Show"
ADD CONSTRAINT chk_pricing_model CHECK ("pricingModel" IN ('cpm', 'spot', 'both'));

ALTER TABLE org_unfy."Show"
ADD CONSTRAINT chk_pricing_model CHECK ("pricingModel" IN ('cpm', 'spot', 'both'));